### ISSUE TITLE
Error checking out rtmidi when building

### ISSUE THREAD

**Issue by sethkush** [SudoMaker/RetroWaveMIDIProxy#1]
`CMake Error at rtmidi-subbuild/rtmidi-populate-prefix/tmp/rtmidi-populate-gitclone.cmake:49 (message):
  Failed to checkout tag: '806e18f575b68c23b26f9398e1b6866b335b5308'`

Changing the tag to '6.0.0' in CMakeLists.txt seems to work.

**Comment by ReimuNotMoe** [comment]
Fixed in b6a9d2dea64aaf4fcc50aa0d7d129dc133f2e801, thx
